[project]
name = "polylith-bug-report"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "ipython>=8.29.0",
    "polylith-cli>=1.23.0",
]
